version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hello_world
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    image: ghcr.io/bilal-s-hamdan/hello-world-backend:latest
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: hello_world
      PGPORT: 5432

  frontend:
    image: ghcr.io/bilal-s-hamdan/hello-world-frontend:latest
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata:
